version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: inflearn-clone-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prismapass
      POSTGRES_DB: inflearn-clone
    volumes:
      - inflearn-clone-db:/var/lib/postgresql/data

volumes: 
  inflearn-clone-db: